name: Deploy to Server

on:
  push:
    branches:
      - master  # `master` салбарт өөрчлөлт орсон тохиолдолд энэ процесс ажиллана.

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Кодыг татаж авах
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. SSH түлхүүрийг ашиглах
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. SSH холболт хийх
      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            # Сервер дээрх проектын хавтас руу орно.
            cd /path/to/your/project

            # GitHub-аас хамгийн сүүлийн код татах
            git pull origin master

            # Хамаарлуудыг дахин суулгах
            npm ci

            # PM2 процессийг дахин эхлүүлэх
            pm2 restart backend-qrmenu
          EOF
