name: Deploy backend-qrmenu

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted   # Self-hosted runner ашиглана
    name: Build & Restart via PM2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm ci

      - name: Restart backend with PM2
        run: pm2 restart backend-qrmenu

      - name: PM2 status
        run: pm2 status
